# named list of all robots
robots:
  cf01:
    enabled: true
    uri: radio://*/100/2M/E7E7E7E701
    initial_position: [-2, 0, 0]
    type: cf21
  cf03:
    enabled: true
    uri: radio://*/100/2M/E7E7E7E703
    initial_position: [-1, 0, 0]
    type: cf21
  cf04:
    enabled: true
    uri: radio://*/100/2M/E7E7E7E704
    initial_position: [0.0, 0.0, 0]
    type: cf21
  cf07: # BAD. cf7 does not want to play.
    enabled: false
    uri: radio://*/80/2M/E7E7E7E707
    initial_position: [0.0, -1.0, 0]
    type: cf21
  # cf08:
    # enabled: false
    # uri: radio://*/120/2M/E7E7E7E708
    # initial_position: [2.0, 0.0, 0]
    # type: cf21s
  cf10:
    enabled: true 
    uri: radio://*/120/2M/E7E7E7E70A
    initial_position: [1.0, 0, 0]
    type: cf21

# Definition of the various robot types
robot_types:
  cf21:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: default_single_marker
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

  cf21_mocap_deck:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: mocap_deck
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

# global settings for all robots
all:
  # firmware logging for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_logging:
    enabled: false
    default_topics:
     # remove to disable default topic
      pose:
        frequency: 10 # Hz
    #custom_topics:
    #  topic_name1:
    #    frequency: 10 # Hz
    #    vars: ["stateEstimateZ.x", "stateEstimateZ.y", "stateEstimateZ.z", "pm.vbat"]
    #  topic_name2:
    #    frequency: 1 # Hz
    #    vars: ["stabilizer.roll", "stabilizer.pitch", "stabilizer.yaw"]
  # firmware parameters for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 2 # 1: PID, 2: mellinger
    ring:
      effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
      solidBlue: 255 # if set to solid color
      solidGreen: 0 # if set to solid color
      solidRed: 0 # if set to solid color
      headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    kalman:
      resetEstimation: 1
  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats
